### ISSUE TITLE
Is there any publications or papers?

### ISSUE THREAD

**Issue by hmf21** [WilyZhao8/GLNet#1]
Hi, it is very impressive work, and thanks for your sharing!
I can not find any publications related to the repo in Google Scholar and arXiv. Will you upload the preprint paper in the future?

**Comment by WilyZhao8** [comment]
> 
Thanks for your interest in our work!
Sorry for not following github due to recent projects, you can get the article from this link: https://ieeexplore.ieee.org/document/9946001

**Comment by hmf21** [comment]
Thanks for your reply!
